config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#welcome' #root define a rota '/' da nossa aplicação
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
   def welcome
     @tasks = Task.all
     
   end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
      def new
      end
      
      def create
          @task = Task.new(params.require(:task).permit(:description, :status))
          @task.save #salva no banco de dados criado
          puts params
          redirect_to root_path #faz nova requisição http, assim nao precisa criar a view create.html.erb
      end
      def edit
        @task = Task.find(params[:id]) #olhando o routes, vemos o nome do param na rota edit
      end
      def update
        @task = Task.find(params[:id]) #o metodo Edit gera na tela o formulario com os dados antigos pré-preenchidos
        #agora em UPDATE é necessario chamar de novo o Task.find para atualizar
        @task.update(params.require(:task).permit(:description, :status))
        redirect_to root_path
      end
      def destroy
         task = Task.find(params[:id]) #nao precisa do @ pq nao temos a view que usara esse objeto
         task.destroy #destroi a tarefa encontrada
         redirect_to root_path
      end      
          
end       

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/welcome.html.erb
<h1>bem vindo ao meu blog!</h1>
<h3>Eis sua lista de tarefas: </h3>
<% @tasks.each do|task| %>
  <%= task.description %>
  <%= link_to 'Editar', edit_task_path(task) %>
  <%= link_to 'Apagar', task_path(task), method: :delete, data: { confirm: 'Quer apagar essa tarefa?' } %>
<% end %>


<em>Criada em <%= Date.today %></em> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MeuBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for @task do |f| %>
   <%= f.label :description, 'Descrição' %>
   <%= f.text_field :description %>
   <%= f.label :status, 'Status' %>
   <%= f.check_box :status %>
   <%= f.submit 'Editar' %>
<% end %> 

app/views/tasks/new.html.erb
<%= form_for Task.new do |f| %>
<%= f.label :description, 'Descrição' %>
<%= f.text_field :description %>
<%= f.label :status, 'Status' %>
<%= f.check_box :status %>
<%= f.submit 'Criar' %>
<% end %>